Fix errors trying to include files that do not exist
The files do not exist and given that there is no context to atttempt to
recreate them, an explanatory message is used instead.

Fixes
```
/src/en/API/sys/cronalarms.rst:4: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: '_build/inc/cronalarms.inc'.
/src/en/API/wifi/wifi_mgmr.rst:4: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: '_build/inc/wifi_mgmr_ext.inc'.
```